[tool.poetry]
name = "students"
version = "0.1.0"
description = "first project"
authors = ["uri ehrlich"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
